### ISSUE TITLE
COMET ERROR: The given api key QQFXdJ5M7GZRGri7CWxwGxPDN is invalid, please check it against the dashboard. Your experiment would not be logged 

### ISSUE THREAD

**Issue by neverstoplearn** [granularai/fabric#9]
(pytorch04) wuwenfu@wuwenfu:/mnt/sda7/fabric$ python train.pyCOMET ERROR: The given api key QQFXdJ5M7GZRGri7CWxwGxPDN is invalid, please check it against the dashboard. Your experiment would not be logged 
For more details, please refer to: https://www.comet.ml/docs/python-sdk/warnings-errors
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    experiment = Experiment()
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/site-packages/polyaxon_client/tracking/no_op.py", line 27, in wrapper
    return f(*args, **kwargs)
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/site-packages/polyaxon_client/tracking/experiment.py", line 52, in __init__
    outputs_store=outputs_store)
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/site-packages/polyaxon_client/tracking/no_op.py", line 27, in wrapper
    return f(*args, **kwargs)
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/site-packages/polyaxon_client/tracking/base.py", line 36, in __init__
    raise PolyaxonClientException('Please provide a valid project.')
polyaxon_client.exceptions.PolyaxonClientException: Please provide a valid project.
how can I fix it？ thanks.

**Comment by sagarverma** [comment]
You can either switch of all the comet functionalities in the code or get an api key from [comet](https://www.comet.ml/) and use it [here](https://github.com/granularai/fabric/blob/bc5dde6a552e1c6a2e4489b70df08a08cd574716/train.py#L29).
